import Head from "next/head";
import Image from "next/image";
import PostList from "../components/PostList";
import styles from "../styles/Home.module.css";

export default function Home({ posts }) {
  console.log(posts);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* bu şekilde de kullanabilirim 
      ancak component kullanmak daha sağlıklı
      <div>
        {posts.map((post) => (
          <div key={post.id}>
            <h1>{post.title}</h1>
            <p>{post.body}</p>
          </div>
        ))}
      </div> */}

      {/* componente posts gönderimi */}
      <PostList posts={posts} />
    </div>
  );
}

//server side olarak build ortamda, asenkron çalışır
//sadece pages klasörü altında export edilebilir
//yani componentlerden export edemez
//return içerisindeki props olmak zorunda
//props içerisindeki obje adı ile çağrılır
export const getStaticProps = async () => {
  const res = await fetch(
    "https://jsonplaceholder.typicode.com/posts?_limit=5"
  );
  const posts = await res.json();

  return {
    props: { posts },
  };
};
