import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import { URL } from "../../environment";

export default function Videos({ videos }) {
  console.log(videos);
  console.log(`${URL}`);
  return (
    <div>
      <Head>
        <title>Videos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {videos.map((video) => (
        <div key={video.id} className={styles.grid}>
          <Link href={`/videos/${video.id}`}>
            <a className={styles.card}>{video.name}</a>
          </Link>
        </div>
      ))}
    </div>
  );
}

//localhost ve production ortamında link kısmı değişeceği için
//kolaylık olması açısından environment ile URL kullanılır
export const getStaticProps = async () => {
  const res = await fetch(`${URL}/api/videos`);
  const videos = await res.json();

  return {
    props: { videos },
  };
};
